server:
  port: 80
spring:
  application:
    name: reggie_take_out
  datasource:
   dynamic:
     primary: sqlserver #设置默认的数据源或者数据源组,默认值即为master
     strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
     datasource:
       sqlserver:
         url: jdbc:sqlserver://172.22.39.128:1433;DatabaseName=smartUIDB;trustServerCertificate=false;integratedSecurity=false;encrypt=false;
         username: sa
         password: 123456
         driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
       mysql:
         driver-class-name: com.mysql.cj.jdbc.Driver
         url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
         username: root
         password: 1234
       datasql:
         driver-class-name: com.mysql.cj.jdbc.Driver
         url: jdbc:mysql://172.22.44.62:3306/digitalj?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
         username: jiangfan
         password: 1234qwer





mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: d:\\img\\